### ISSUE TITLE
FR: Change samples to use new 0.2.3 connect infrastructure.

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/cloud-bigtable-examples#113]
import com.google.cloud.bigtable.hbase.BigtableConfiguration

Connection connection = BigtableConfiguration.connect(projectId, zone, cluster);

… OR ...

Configuration conf = BigtableConfiguration.configure(projectId, zone, cluster);
Connection connection = BigtableConfiguration.connect(conf);

**Comment by sduskis** [comment]
I did this work at some point.
