### ISSUE TITLE
quick start is broken

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/cloud-bigtable-examples#120]
Following the instructions in quick start, then everything at the shell prompt fails:
hbase(main):004:0> create table 'test', 'cf'
NoMethodError: undefined method `table' for #<Object:0x71978f46>

hbase(main):005:0> list
TABLE
Exception `NativeException' at /usr/local/google/home/rennie/gitrepos/cloud-bigtable-examples/quickstart/thirdparty/ruby/hbase/admin.rb:48 - java.io.IOException: Failed to listTables

ERROR: PERMISSION_DENIED: Project has not enabled the API. Please use Google Developers Console to activate the 'bigtabletableadmin' API for your project.

The API is enabled:
![image](https://cloud.githubusercontent.com/assets/11778530/12210654/68749fb2-b610-11e5-976c-b08f57d7e1c1.png)

**Comment by lesv** [comment]
That is not what the picture shows.

On Fri, Jan 8, 2016 at 2:02 PM, SurferJeff <notifications@github.com> wrote:

> Following the instructions in quick start, then everything at the shell
> prompt fails:
> hbase(main):004:0> create table 'test', 'cf'
> NoMethodError: undefined method `table' for #Object:0x71978f46
>
> hbase(main):005:0> list
> TABLE
> Exception `NativeException' at
> /usr/local/google/home/rennie/gitrepos/cloud-bigtable-examples/quickstart/thirdparty/ruby/hbase/admin.rb:48
> - java.io.IOException: Failed to listTables
>
> ERROR: PERMISSION_DENIED: Project has not enabled the API. Please use
> Google Developers Console to activate the 'bigtabletableadmin' API for your
> project.
>
> The API is enabled:
> [image: image]
> <https://cloud.githubusercontent.com/assets/11778530/12210654/68749fb2-b610-11e5-976c-b08f57d7e1c1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/issues/120>
> .
>



-- 


*  •  **Les Vogel*
*  •  *Cloud Developer Relations
*  •  *lesv@google.com
*  •  *+1-4 <%2B1-650-338-7103>08-676-7023

**Comment by lesv** [comment]
Oops - I read it wrong.  :(

On Fri, Jan 8, 2016 at 4:05 PM, Les Vogel <lesv@google.com> wrote:

> That is not what the picture shows.
>
> On Fri, Jan 8, 2016 at 2:02 PM, SurferJeff <notifications@github.com>
> wrote:
>
>> Following the instructions in quick start, then everything at the shell
>> prompt fails:
>> hbase(main):004:0> create table 'test', 'cf'
>> NoMethodError: undefined method `table' for #Object:0x71978f46
>>
>> hbase(main):005:0> list
>> TABLE
>> Exception `NativeException' at
>> /usr/local/google/home/rennie/gitrepos/cloud-bigtable-examples/quickstart/thirdparty/ruby/hbase/admin.rb:48
>> - java.io.IOException: Failed to listTables
>>
>> ERROR: PERMISSION_DENIED: Project has not enabled the API. Please use
>> Google Developers Console to activate the 'bigtabletableadmin' API for your
>> project.
>>
>> The API is enabled:
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/11778530/12210654/68749fb2-b610-11e5-976c-b08f57d7e1c1.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/issues/120>
>> .
>>
>
>
>
> --
>
>
> *  •  **Les Vogel*
> *  •  *Cloud Developer Relations
> *  •  *lesv@google.com
> *  •  *+1-4 <%2B1-650-338-7103>08-676-7023
>
>
>


-- 


*  •  **Les Vogel*
*  •  *Cloud Developer Relations
*  •  *lesv@google.com
*  •  *+1-4 <%2B1-650-338-7103>08-676-7023

**Comment by lesv** [comment]
Were you on VM instance or your machine?  Linux?  Windows?  Mac? 

Did you have a GOOGLE_APPLICATION_CREDENTIALS set to another project?
