### ISSUE TITLE
Update python/thrift/appengine-ssl-gateway to use Container-VM image

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/cloud-bigtable-examples#166]
Currently the [python/thrift/appengine-ssl-gateway](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/python/thrift/appengine-ssl-gateway) sample is using the [Container-Optimized Google Compute Engine Image](https://cloud.google.com/compute/docs/containers/container_vms) `--image container-vm`. There is a warning that this is superseded by the [Container-VM Image](https://cloud.google.com/compute/docs/containers/vm-image/) `--image gci-beta-... --image-project google-containers`.

We should update the sample to use the new image.

**Comment by tswast** [comment]
@lesv FYI

**Comment by tswast** [comment]
Alternatively, we could use the CoreOS image. This is what we use in the CP 100 course since it includes a Docker installation.

**Comment by lesv** [comment]
Yes - since it's public.  It's fast.

**Comment by meredithslota** [comment]
Deprioritized, closing. If anyone feels strongly about this, please reply/reopen! :)
