### ISSUE TITLE
Spark READMEs are out of date and incomplete

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/cloud-bigtable-examples#179]
The README files for all three of our [Spark examples](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/scala) need updates:
- The [spark-pubsub README](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/scala/spark-pubsub) tells you to use bdutil to create Compute Engine instances. It should tell you to use Cloud Dataproc instead.
- The [spark-standalone-wordcount README](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/scala/spark-standalone-wordcount) and [spark-streaming-wordcount README](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/scala/spark-streaming-wordcount) are both incomplete.

**Comment by lesv** [comment]
Yep - Totally agree

**Comment by tswast** [comment]
Obsolete now that the spark samples have been removed?

**Comment by aeneaswiener** [comment]
I am interested in accessing BigTable from PySpark. Is this viable to do currently / are you planning to provide working examples again for this use case?

**Comment by lesv** [comment]
It really depends on your use case.  The HBase Spark connector currently uses the old HBase API's. (pre 1.0).  This means that you can't really use Cloud Bigtable as a source in Spark.  On the other hand, if you have another kind of source, and just wish to write to Cloud Bigtable, you can use our [Python API's](https://cloud.google.com/bigtable/docs/samples-python-hello) to write.

**Comment by lesv** [comment]
I'm going to close this issue as the work has been done - That @hegemonic asked for.

**Comment by aeneaswiener** [comment]
My specific use case is to read data from BigTable. Do I understand correctly that reading data stored in BigTable from PySpark is currently not possible? If not possible, what is blocking it? (Google Cloud Platform support have asked me to raise this query in this issue.)

**Comment by lesv** [comment]
You can totally read data, and using the Hadoop connector.  It's just some of the Spark specific features aren't yet available.

@garye @sduskis FYI

**Comment by aeneaswiener** [comment]
Where could I find information on how to read data? A link to code example or documentation would be useful if you have it.

**Comment by lesv** [comment]
Did you look at the [link](https://cloud.google.com/bigtable/docs/samples-python-hello) above?  Or are you looking for a complete Hadoop sample w/ Python?

@tswast FYI

**Comment by aeneaswiener** [comment]
I am looking for a PySpark example.

**Comment by lesv** [comment]
You might wish to look at [SO](http://stackoverflow.com/questions/40371827/how-to-read-and-write-data-to-google-bigtable-in-pyspark-application)
