### ISSUE TITLE
Raw /blob/v2-prework/quickstart/README.md uses auto-numbering

### ISSUE THREAD

**Issue by carterpage** [GoogleCloudPlatform/cloud-bigtable-examples#180]
The README.md file should be readable as raw text.

It currently reads:

`1. Go to...`
`1. Create...`
`1. Select...`

It should read:

`1. Go to...`
`2. Create...`
`3. Select...`

**Comment by lesv** [comment]
That's a standard for markdown, so it's easy to insert text.  I'll change it if you insist.

**Comment by meredithslota** [comment]
No reply in several years. :) Closing as `obsolete`.
