### ISSUE TITLE
Can we make projectID and instanceID parameters for runtime rather than properties at compile time?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/cloud-bigtable-examples#204]
The use case I have in mind is limited specifically to the export operation, which is something someone may want to do in a backup scenario, while having no knowledge (or interest) in Java (ie, they use Bigtable via another language). In that case, having to compile a jar just to set two parameters seems a bit strange.

Is there any way we can make it so that the `export-table` operation that is submitted as a job to Dataproc accepts those as parameters?

In other words, currently we require:

```sh
$ git clone https://github.com/GoogleCloudPlatform/cloud-bigtable-examples.git
$ cd cloud-bigtable-examples/java/dataproc-wordcount
$ mvn clean package -Dbigtable.projectID=my-project -Dbigtable.instanceID=my-instance
$ gcloud dataproc clusters create my-cluster --zone us-central1-c
$ gcloud dataproc jobs submit hadoop --cluster my-cluster \
  --class com.google.cloud.bigtable.mapreduce.Driver \
  --jar target/wordcount-mapreduce-0-SNAPSHOT-jar-with-dependencies.jar \
  export-table my-table gs://my-bucket/export
```

I'd like it to be

```sh
$ curl -O https://some/path/to/bigtable-export.jar
$ gcloud dataproc clusters create my-cluster --zone us-central1-c
$ gcloud dataproc jobs submit hadoop --cluster my-cluster \
  --class com.google.cloud.bigtable.mapreduce.Driver \
  --jar bigtable-export.jar --projectID=my-project --instanceID=my-instance \
  export-table todo gs://my-bucket/export
```

Ultimately this should be .. way easier for everyone with something like

```sh
$ gcloud bigtable clusters export-table table-id --cluster us-central1-a/cluster-id
```

but until then, the Dataproc way seems to be an OK compromise...

/cc @lesv @tswast

**Comment by sduskis** [comment]
I think this should be done in cloud-bigtable-client.  I'll work on this.

**Comment by sduskis** [comment]
This was done in cloud-bigtable-client.  The instructions can be found [here](https://cloud.google.com/bigtable/docs/importing-sequence-files).
