### ISSUE TITLE
ERROR IN APLICATION STARTUP IN GOOGLE CLOUD

### ISSUE THREAD

**Issue by carlosamurillo** [GoogleCloudPlatform/cloud-bigtable-examples#217]
Hi, I am tried to upload this project to testing, and first I had to change in app.yaml "vm: true" to "env: flex", then the project compile but when is starting in the servers get this error: 

[INFO] GCLOUD: latest: digest: sha256:a1ca8f509a49ced6d17040212896b36555a4ae17cdfbacf882389f1fbd9fb8f5 size: 6966
[INFO] GCLOUD: DONE
[INFO] GCLOUD: --------------------------------------------------------------------------------
[INFO] GCLOUD: 
[INFO] GCLOUD: Updating service [bigtable]...
[INFO] GCLOUD: .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................failed.
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [9] 
[INFO] GCLOUD: Application startup error:
[INFO] GCLOUD: Archive:  /var/lib/jetty/webapps/root.war
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/META-INF/MANIFEST.MF  
[INFO] GCLOUD:    creating: /var/lib/jetty/webapps/root/WEB-INF/
[INFO] GCLOUD:    creating: /var/lib/jetty/webapps/root/WEB-INF/classes/
[INFO] GCLOUD:    creating: /var/lib/jetty/webapps/root/WEB-INF/classes/com/
[INFO] GCLOUD:    creating: /var/lib/jetty/webapps/root/WEB-INF/classes/com/example/
[INFO] GCLOUD:    creating: /var/lib/jetty/webapps/root/WEB-INF/classes/com/example/bigtable/
[INFO] GCLOUD:    creating: /var/lib/jetty/webapps/root/WEB-INF/lib/
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/favicon.ico  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/apacheds-kerberos-codec-2.0.0-M15.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/commons-codec-1.3.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/commons-collections-3.2.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/commons-logging-1.2.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/gson-2.3.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hadoop-annotations-2.5.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hadoop-auth-2.5.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hadoop-common-2.4.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hadoop-yarn-api-2.5.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hbase-annotations-1.2.4.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hbase-client-1.2.4.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/htrace-core-3.1.0-incubating.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/httpclient-4.0.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/httpcore-4.0.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/jackson-core-asl-1.9.13.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/jackson-mapper-asl-1.9.13.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/joni-2.1.2.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/jsr305-3.0.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/jstl-1.2.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/log4j-1.2.16.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/netty-tcnative-boringssl-static-1.1.33.Fork26.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/xz-1.0.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/web.xml  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/META-INF/maven/com.example.google.cloud.bigtable/helloWorld/pom.xml  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/META-INF/maven/com.example.google.cloud.bigtable/helloWorld/pom.properties  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/index.jsp  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/apacheds-i18n-2.0.0-M15.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/api-util-1.0.0-M20.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/bigtable-hbase-1.2-0.9.5.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/jaxb-api-2.2.2.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/jcodings-1.0.8.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/metrics-core-2.2.0.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/netty-3.6.2.Final.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/paranamer-2.3.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/protobuf-java-3.0.2.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/stax-api-1.0-2.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/zookeeper-3.4.6.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/com/example/bigtable/BigtableHelloWorld.class  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/activation-1.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/appengine-api-1.0-sdk-1.9.34.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/classes/com/example/bigtable/BigtableHelper.class  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/api-asn1-api-1.0.0-M20.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/avro-1.7.4.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/commons-cli-1.3.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/commons-compress-1.4.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/commons-io-2.4.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/commons-lang-2.6.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/guava-19.0.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hadoop-mapreduce-client-core-2.5.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hadoop-yarn-common-2.5.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hbase-common-1.2.4.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/hbase-protocol-1.2.4.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/netty-all-4.0.23.Final.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/slf4j-api-1.7.7.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/slf4j-log4j12-1.6.1.jar  
[INFO] GCLOUD:   inflating: /var/lib/jetty/webapps/root/WEB-INF/lib/snappy-java-1.0.4.1.jar  
[INFO] GCLOUD: -XX:InitialHeapSize=514850816 -XX:MaxHeapSize=514850816 -XX:+ParallelRefProcEnabled -XX:+PrintCommandLineFlags -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC 
[INFO] GCLOUD: openjdk version "1.8.0_121"
[INFO] GCLOUD: OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
[INFO] GCLOUD: OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
[INFO] GCLOUD: 
[INFO] GCLOUD: 2017-03-30 19:05:46.150:INFO::main: Logging initialized @2800ms to org.eclipse.jetty.util.log.StdErrLog
[INFO] GCLOUD: 2017-03-30 19:05:47.610:INFO:oejs.SetUIDListener:main: Setting umask=02
[INFO] GCLOUD: 2017-03-30 19:05:47.651:INFO:oejs.SetUIDListener:main: Opened ServerConnector@28d25987{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] GCLOUD: 2017-03-30 19:05:47.652:INFO:oejs.SetUIDListener:main: Setting GID=999
[INFO] GCLOUD: 2017-03-30 19:05:47.661:INFO:oejs.SetUIDListener:main: Setting UID=999
[INFO] GCLOUD: 2017-03-30 19:05:47.673:INFO:oejs.Server:main: jetty-9.4.1.v20170120
[INFO] GCLOUD: 2017-03-30 19:05:47.741:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 0
[INFO] GCLOUD: 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:57 min
[INFO] Finished at: 2017-03-30T14:12:08-05:00
[INFO] Final Memory: 27M/272M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.0.0:deploy (default-cli) on project helloWorld: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.0.0:deploy failed: Non zero exit: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by meredithslota** [comment]
Closing this as it is likely obsolete. If you are still seeing issues like this, please file an issue at https://github.com/googleapis/java-bigtable/issues which is more actively maintained. Thanks!
