### ISSUE TITLE
This quickstart example only runs on google cloud shell, not on local machine

### ISSUE THREAD

**Issue by PhyFrancis** [GoogleCloudPlatform/cloud-bigtable-examples#226]
I tried to run it on my linux desktop and it doesn't spin up. I think this is an intended behavior and we should explicitly say this in the readme file.

**Comment by sduskis** [comment]
I run it on my development machines all of the time   The cloud shell is a convenience rather than a requirement.  You need to install gcloud on your machine in order to make it all work properly.  If that doesn't work, can you please describe the problem you're experiencing?

**Comment by PhyFrancis** [comment]
@sduskis  Thanks for the quick response! I did install gcloud on my machine. I will try to describe the problem. I did:
1. Start a bigtable instance in my cloud project.
2. On my lcoal machine, run `gcloud components update && gcloud components install alpha beta`
3. On my local machine, run `gcloud init` and choose my account and the cloud project.
4. On my local machine, run `./quickstart.sh`
The output is:
```
NativeException: java.io.IOException: java.lang.reflect.InvocationTargetException
  initialize at /usr/local/google/home/daiqianzhang/Work/cloud-bigtable-examples/quickstart/thirdparty/ruby/hbase/hbase.rb:42
      (root) at thirdparty/hirb.rb:132
```

**Comment by PhyFrancis** [comment]
Okay I figured it out. It's because I didn't set the environment variable `GOOGLE_APPLICATION_CREDENTIALS`. After I follow the instructions at https://developers.google.com/identity/protocols/application-default-credentials, the quickstart script works fine locally. 

I believe in the cloud shell, this environment variable is set automatically (or it's not needed at all), so I was mistakenly thinking that the quickstart example only works in cloud shell.

But still this is a good thing to put into the readme.
