### ISSUE TITLE
Remove disable and other non-supported features from quickstart

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-examples#249]
There's an HBase requirement to disable tables before deleting them.  The Ruby shell helpfully checks that the table is disabled before deleting.  That doesn't make sense for CBT, so we should just remove the disable requirement.

There are plenty of other features that CBT doesn't support, so we should investigate which shell features those are, and then remove the code from the quickstart.

**Comment by meredithslota** [comment]
We are removing this code sample in https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/pull/386 — the more recently updated quickstart is in the Java folder.
