### ISSUE TITLE
Simple Cloud Bigtable Performance test example does not execute successfully

### ISSUE THREAD

**Issue by danieldeleo** [GoogleCloudPlatform/cloud-bigtable-examples#264]
The https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/simple-performance-test example does not work after following instructions verbatim.

**Comment by sduskis** [comment]
Can you please try this:

mvn clean compile exec:java -Dexec.mainClass="com.example.bigtable.simpleperf.WritePerfTest" -Dexec.args="[projectid] [instanceid] [tableid] [rowCount] [valueSize]"

where you replace each bracketed item with an appropriate value.

**Comment by danieldeleo** [comment]
That worked! Thanks!

**Comment by danieldeleo** [comment]
Also for this line: 

https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/55b513b28248c54e661b3e22bdeb65c477d0e641/java/simple-performance-test/src/main/java/com/example/bigtable/simpleperf/WritePerfTest.java#L96 

the input parameter "PRINT_COUNT" should be replaced with "toIntExact(rowCount)" as it's reporting how much time all rows took to write
