### ISSUE TITLE
Is there a way to choose the region for dataflow job

### ISSUE THREAD

**Issue by mahmoudhanafy** [GoogleCloudPlatform/cloud-bigtable-examples#283]
I was trying this example:
> SourceRowCount - Reading from Cloud Bigtable

but the job always starts at region `us-central1`. I've tried to bypass parameter `-Dbigtable.region=europe-west1` but found that region still `us-central1`

**Comment by sduskis** [comment]
Are you looking to set the Dataflow region?  If so, you need the Dataflow settings, and not the Bigtable specific settings.

I don't know what the default key is off hand.

**Comment by mahmoudhanafy** [comment]
should I set it at the code? or is there a way to pass this parameter through the terminal?

**Comment by sduskis** [comment]
`--[paramenterId]=[value]` will be passed through the terminal.  It looks like `--region=[region] and `--zone=[zone]` ought to work according to [these docs](https://cloud.google.com/dataflow/docs/concepts/regional-endpoints).

**Comment by mahmoudhanafy** [comment]
I've tried sending --region. but it was considered as a parameter to maven, not to the main class.

**Comment by sduskis** [comment]
Ah, got it.  For now, you'll have to change the [pom.xml](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/dataflow-connector-examples/pom.xml#L181) locally.  We'll have to think about how to improve the example with new parameters.

**Comment by meredithslota** [comment]
Regional endpoints for Dataflow are documented here: https://cloud.google.com/dataflow/docs/concepts/regional-endpoints as noted above. There's a section for configuring different sources as well, but it doesn't yet include Bigtable. b/63408022 is a potentially relevant internal documentation request, but we likely won't be improving the sample as requested above. 

Here's documentation the supported Dataflow Connector for Bigtable: https://cloud.google.com/bigtable/docs/hbase-dataflow-java — those code samples live (and are maintained) here: https://github.com/GoogleCloudPlatform/java-docs-samples/tree/492d49f867249f29acbb9e15ba395542d3fe17d5/bigtable/beam/helloworld/src/main/java
