### ISSUE TITLE
Add Bigtable quickstart 

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/cloud-bigtable-examples#291]
https://github.com/jabubake/nodejs-bigtable/blob/master/samples/README.md#quickstart
Please see expected quickstart for Bigtable here :
https://github.com/jabubake/nodejs-bigtable/blob/master/samples/quickstart.js
(Read a row from an existing table)

@sduskis FYI

**Comment by sduskis** [comment]
This bug should likely be on https://github.com/GoogleCloudPlatform/cloud-bigtable-client rather than the examples repo.

**Comment by jabubake** [comment]
I was trying to keep them together with the java samples that currently exist. We should ideally look at moving them to https://github.com/GoogleCloudPlatform/java-docs-samples.

Also, this repo is already referenced https://github.com/GoogleCloudPlatform/cloud-bigtable-client#using-the-java-client

**Comment by sduskis** [comment]
Quickstarts should also be on top-level client README pages.  Is there a good way to manage that from github?

**Comment by jabubake** [comment]
I wish this was easier : 
we do use https://github.com/campoy/embedmd for community articles (I'll look at doing that for the Node.js client and the Java HBase client as examples).
