### ISSUE TITLE
Scaling tool should consider storage utilization

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/cloud-bigtable-examples#305]
The scaling tool does not consider [storage utilization per node](https://cloud.google.com/bigtable/quotas#storage-per-node) when it resizes a cluster. It's already a best practice to look at storage utilization, and it will become a hard requirement on 2018-10-01, when we'll prevent users from exceeding the maximum utilization per node.

We should update the tool to look at the metric `bigtable.googleapis.com/cluster/storage_utilization` and factor that metric into the calculation of how many nodes to add or remove.

GoogleCloudPlatform/python-docs-samples#1695 tracks the same issue, but for Python.

**Comment by meredithslota** [comment]
Closing as a "Won't Fix".
