### ISSUE TITLE
bigtable shc example missing com.hortonworks shc-core v1.1.3 spark 2.4 not found.

### ISSUE THREAD

**Issue by jkleckner** [GoogleCloudPlatform/cloud-bigtable-examples#317]
If you clone this repo and simply run `cd cloud-bigtable-examples/scala/bigtable-shc ; sbt compile`, it will fail to find the specified version of `shc-core` which is version `1.1.3` for `spark 2.4`.

Should the prerequisites in the `README.md` also specify that you need to download and compile/install the `shc` components?

```
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.hortonworks:shc-core:1.1.3-2.4-s_2.11 (/private/tmp/cloud-bigtable-examples/scala/bigtable-shc/build.sbt#L7-8)
[warn] 		  +- com.example.bigtable.spark.shc:cloud-bigtable-dataproc-spark-shc_2.11:0.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.hortonworks#shc-core;1.1.3-2.4-s_2.11: not found
```

The [README.md file](https://github.com/hortonworks-spark/shc/blob/master/README.md) indicates that an earlier 1.1.1 version is not uploaded as well.
```
Note: com.hortonworks:shc-core:1.1.1-2.1-s_2.11 has not been uploaded to spark-packages.org, but will be there soon.
```

**Comment by jaceklaskowski** [comment]
> Should the prerequisites in the README.md also specify that you need to download and compile/install the shc components?

Absolutely. And they are in https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/scala/bigtable-shc#prerequisites:

> NOTE: The project uses Apache Spark - Apache HBase Connector 1.1.3-2.4 that has not been released to any of the known public repositories. You should package the library locally as described in the Compile section of the official documentation of Apache Spark - Apache HBase Connector.

Do you think it should be (re)worded differently or be in another place?

**Comment by sduskis** [comment]
@jaceklaskowski thanks for jumping in.  I didn't realize we were using a non-released version of shc.  We probably should change that.

**Comment by jkleckner** [comment]
@jaceklaskowski Doh!  Obviously moving too fast and skimming.  Thank you and sorry for the noise.
I just didn't want to figure out how to put the artifacts into our repository manually.

@sduskis I guess you could consider it "well-defined" at the source level, just not "published" at the artifact level...
