### ISSUE TITLE
Golang example?

### ISSUE THREAD

**Issue by ptomasroos** [GoogleCloudPlatform/cloud-bigtable-examples#32]
Will there be a rest api for this service?

**Comment by lesv** [comment]
We just launched the HBase Java API's, we will roll out other API's as they become available, though I have nothing to announce at this time.  

One of our [examples](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/python/rest) (which somehow didn't get linked from the main readme) shows how to setup an HBase REST/Thrift server with Python clients.  You could easily do REST with that.  We also show a simple java based [JSON server running on Managed VMs](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/managed-vms).

**Comment by lesv** [comment]
Take a look at: https://godoc.org/google.golang.org/cloud/bigtable

**Comment by lesv** [comment]
https://godoc.org/google.golang.org/cloud/bigtable

**Comment by ptomasroos** [comment]
Many thanks guys, this is just great!
