### ISSUE TITLE
Unauthenticated error during SaveAsNewAPIHadoopDataset during Spark Streaming

### ISSUE THREAD

**Issue by jresgar** [GoogleCloudPlatform/cloud-bigtable-examples#328]
I'm following the cloud-bigtable-dataproc-streaming-spark-wordcount example to set up a Spark streaming job consuming from Kafka and writing to Bigtable. 

Using the dependency versions from that example end in unauthenticated errors caused by Timeouts when trying to make any calls past the Bigtable connection (admin.tableExists() or JavaPairRDD.saveAsNewAPIHadoopDataset()):
`Refreshing the OAuth token
Retrying failed call. Failure #1, got: Status{code=UNAUTHENTICATED, description=Unexpected failure get auth token, cause=java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.getHeader(RefreshingOAuth2CredentialsInterceptor.java:290)`

If I bump up bigtable-hbase-1.x-hadoop to something like 1.9, I get past the authenticated timeouts, but get another unathenticated error when hitting the saveAsNewAPIHadoopDataset(): 
`Retrying failed call. Failure #1, got: Status{code=UNAUTHENTICATED, description=Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project., cause=null} on channel 34.
Trailers: Metadata(www-authenticate=Bearer realm="https://accounts.google.com/",bigtable-channel-id=34)`

I haven't found much luck at all upgrading to bigtable-hbase-2.x-hadoop versions, and mostly get ClassNotFoundErrors and several classes are marked deprecated.

POM:
`
<properties>
        <scala.version>2.11.0</scala.version>
        <spark.version>2.3.3</spark.version>
        <hbase.version>1.3.1</hbase.version>
        <bigtable.version>1.9.0</bigtable.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.7.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>26.0-jre</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-logging</artifactId>
            <version>1.74.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>protobuf-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming-kafka-0-10_2.11</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming_2.11</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>${spark.version}</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud.bigtable</groupId>
            <artifactId>bigtable-hbase-2.x-hadoop</artifactId>
            <version>${bigtable.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-server</artifactId>
            <version>${hbase.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-client</artifactId>
            <version>${hbase.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-bigtable</artifactId>
            <version>0.95.0-alpha</version>
        </dependency>
`

**Comment by jresgar** [comment]
I think I've narrowed it down to setting up the Batch configuration. Removing the `conf.set(BigtableOptionsFactory.BIGTABLE_HOST_KEY, BigtableOptions.BIGTABLE_BATCH_DATA_HOST_DEFAULT)` from the setBatchConfigOptions authenticates fine, but it seems to just run forever and never actually commit the Puts to Bigtable. Is there a different way I need to be authenticated to the batch bigtable host?

**Comment by rahulKQL** [comment]
We are really sorry for the trouble, It seems you are also facing similar issue added in [CBT#2182](https://github.com/googleapis/cloud-bigtable-client/issues/2182).

As of the moment, all the previous bigtable releases (i.e. **bigtable's <= 1.11.0**) are facing this issue in the case of **batch mode**(_This issue is a temporary issue, a fix will be added soon_).

A workaround has been added in bigtable's >= 1.11.1-SNAPSHOT releases by @igorbernstein2.

Or another temporary workaround(which can be used for running this examples) would be to configure Bigtable host:
```java
configure.set(BigtableOptionsFactory.BIGTABLE_HOST_KEY, BigtableOptions.BIGTABLE_DATA_HOST_DEFAULT);
```

**Comment by igorbernstein2** [comment]
version 1.12.0 has been released and should address this problem.

**Comment by jresgar** [comment]
Sorry for the late response, I was out of town. Upgrading to 1.12.0 solved the unauthenticated issue. However, I'm still getting a "no route to host" exception like I was when running under the default data host name in my first comment.

**Comment by igorbernstein2** [comment]
That's odd. Can you try simplifying the example to a simple java application:

```java
public class Main {
  private static final String PROJECT_ID = "your-project-id";
  private static final String INSTANCE_ID = "your-instance-id";
  private static final String TABLE_ID = "your-table-id";

  public static void main(String[] args) throws Exception {
    Configuration config = BigtableConfiguration.configure(PROJECT_ID, INSTANCE_ID);

    config.set(BigtableOptionsFactory.BIGTABLE_USE_CACHED_DATA_CHANNEL_POOL, "true");
    config.set(BigtableOptionsFactory.BIGTABLE_HOST_KEY, BigtableOptions.BIGTABLE_BATCH_DATA_HOST_DEFAULT);
    config.set(BigtableOptionsFactory.INITIAL_ELAPSED_BACKOFF_MILLIS_KEY, String.valueOf(TimeUnit.SECONDS.toMillis(5)));
    config.set(BigtableOptionsFactory.MAX_ELAPSED_BACKOFF_MILLIS_KEY, String.valueOf(TimeUnit.MINUTES.toMillis(5)));
    config.set(BigtableOptionsFactory.BIGTABLE_ASYNC_MUTATOR_COUNT_KEY, "0");

    try (Connection c = BigtableConfiguration.connect(config)) {
      try (Table table = c.getTable(TableName.valueOf(TABLE_ID))) {
        try (ResultScanner scanner = table.getScanner(new Scan().setLimit(1))) {
          for (Result result : scanner) {
            System.out.println(Bytes.toString(result.getRow()));
          }
        }
      }
    }
  }
}
```

**Comment by jresgar** [comment]
Yeah I still get a NoRouteToHostException when running that example. I believe it might be an issue with a corporate firewall or proxy. If I create a Dataproc job, everything runs fine, it's just locally that the exception is thrown.

 ```
Retrying failed call. Failure #1, got: Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: batch-bigtable.googleapis.com/2607:f8b0:4000:80e:0:0:0:200a:443
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.grpc.netty.shaded.io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:312)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1340)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:532)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:50)
	at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:136)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:532)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:38)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:522)
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by igorbernstein2** [comment]
I think you are right that it's a firewall issue. Try doing this in your shell

```sh
DATAHOST=batch-bigtable.googleapis.com
P=your-project-id
I=your-instance-id
T=your-table-id
TK=$(gcloud auth print-access-token)
TYPE="Content-type:text/json"

curl -X post -H $TYPE -d@-  https://$DATAHOST/v2/projects/$P/instances/$I/tables/$T:readRows?access_token=$TK   <<EOF
{
  "rows_limit": 1
}
EOF
```

**Comment by jresgar** [comment]
yeah that command returns a row from my table.

**Comment by igorbernstein2** [comment]
Hmm, I would've expected that to fail. Do you know if curl is configured to connect via a proxy? If so, you might need to configure grpc to use the proxy as well using using the system properties `-Dhttps.proxyHost=HOST -Dhttps.proxyPort=PORT`

**Comment by jresgar** [comment]
Okay yeah that makes sense. Yeah that worked when running locally. Thank you so much for your help!
