### ISSUE TITLE
Invalid ENV format

### ISSUE THREAD

**Issue by bx5974** [GoogleCloudPlatform/cloud-bigtable-examples#33]
Invalid ENV format in Docker File

**Comment by lesv** [comment]
Missed this -- sorry - It's valid for 1.5, which version of Docker are you using?

**Comment by lesv** [comment]
Are you on Windows?  I could imagine missing something there.

**Comment by lesv** [comment]
I looked at all three Dockerfiles, and they appear correct.  From https://docs.docker.com/reference/builder/#env  ENV can be either:
ENV <key> <value>
ENV <key>=<value> ...
