### ISSUE TITLE
      <systemPath>${JAVA_HOME}/lib/tools.jar</systemPath> in pom.xml not known

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/cloud-bigtable-examples#46]
In a IDE that starts from the GUI, not a terminal I see an error in the pom.xml
at       <systemPath>${JAVA_HOME}/lib/tools.jar</systemPath>

${JAVA_HOME} is not defined in GUI tools.
We need to find a portable and reliable way for this setting.

**Comment by lesv** [comment]
Fixed -- Thanks.
