### ISSUE TITLE
Quickstart should install HBase from a Cloud Storage bucket

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/cloud-bigtable-examples#78]
In #76, the quickstart was updated to install HBase from an Apache mirror. The issue with this approach is that as soon as HBase 1.1.2 is released, HBase 1.1.1 will no longer be available from the Apache mirror. As a result, the quickstart will stop working.

It would be better to download HBase from a Cloud Storage bucket, as we did prior to #76.

**Comment by lesv** [comment]
No longer an issue.
