### ISSUE TITLE
FR: Dataflow pubsub word count never quits

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/cloud-bigtable-examples#90]
It should be rewritten to call:
`mockUnboundedSource` or `waitToFinish` from [DataflowExampleUtils](https://github.com/GoogleCloudPlatform/DataflowJavaSDK-examples/blob/master/src/main/java/com/google/cloud/dataflow/examples/common/DataflowExampleUtils.java)

**Comment by sduskis** [comment]
This is intended behavior.  The whole point of the unbounded Pub/Sub dataflow is to wait for messages.

**Comment by lesv** [comment]
Ah - I may mention unbounded in either the README or the name.
