### ISSUE TITLE
Quickstart fails w/ Java8

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/cloud-bigtable-examples#94]
Weird error if your running w/ Java 8 -- should either mitigate (if possible) or detect in the script.

**Comment by sduskis** [comment]
+1 on detection.  There might be something we could do via maven pom.xml files, but I'm not sure.

**Comment by lesv** [comment]
Working on fixing it now.

**Comment by lesv** [comment]
Fixed. Works for Java7 & Java8 -- Thanks to Solomon for the method.  (cleaner than my way)
